// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAs2t4qhW6LjUAyFGoSoK6d0ew-dQLS9KE',
    appId: '1:91422084282:web:a1d6a39cc58c377a6ac683',
    messagingSenderId: '91422084282',
    projectId: 'zc-mobile-project',
    authDomain: 'zc-mobile-project.firebaseapp.com',
    databaseURL: 'https://zc-mobile-project-default-rtdb.firebaseio.com',
    storageBucket: 'zc-mobile-project.firebasestorage.app',
    measurementId: 'G-CY6XNGHTJ2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_UCn4iwklEMgRuRQkExm4HQTu2-JRAUQ',
    appId: '1:91422084282:android:d00c78f0f89802646ac683',
    messagingSenderId: '91422084282',
    projectId: 'zc-mobile-project',
    storageBucket: 'zc-mobile-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVAjJtRJ7-xQX0wNW3DOxpM_7UG1OkWkc',
    appId: '1:91422084282:ios:4e0d4a9e265290d36ac683',
    messagingSenderId: '91422084282',
    projectId: 'zc-mobile-project',
    storageBucket: 'zc-mobile-project.firebasestorage.app',
    iosBundleId: 'com.example.clustergo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVAjJtRJ7-xQX0wNW3DOxpM_7UG1OkWkc',
    appId: '1:91422084282:ios:4e0d4a9e265290d36ac683',
    messagingSenderId: '91422084282',
    projectId: 'zc-mobile-project',
    storageBucket: 'zc-mobile-project.firebasestorage.app',
    iosBundleId: 'com.example.clustergo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAs2t4qhW6LjUAyFGoSoK6d0ew-dQLS9KE',
    appId: '1:91422084282:web:4bc231bc1f6265656ac683',
    messagingSenderId: '91422084282',
    projectId: 'zc-mobile-project',
    authDomain: 'zc-mobile-project.firebaseapp.com',
    databaseURL: 'https://zc-mobile-project-default-rtdb.firebaseio.com',
    storageBucket: 'zc-mobile-project.firebasestorage.app',
    measurementId: 'G-636JMFWDXV',
  );
}
